### PR TITLE
Support for Mautic 3

### PR DESCRIPTION
**Pull request by kuzmany**
This PR added support for Mautic 3
Should work also on Mautic2

### CODE REVIEW

**Comment by ChrisRAoW** [comment]
thanks, I will check it out and test it.

**Comment by kylebehse** [comment]
@ChrisRAoW - Hey Chris, have you had a chance to review this? Is this all it needs to work in Mautic 3?

**Comment by buzzworkers** [comment]
Is this already integrated in the main branch ?

**Comment by oliversum-ch** [comment]
hey @ChrisRAoW, are you still maintaining this project?

**Comment by kuzmany** [comment]
We're using this code in production

**Pull request merged**
